apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  SEED_USERNAME: ZGVtbw==
  SEED_USER_PASSWORD: ZGVtbw==
  RABBITMQ_DEFAULT_USER: ZGVtbw==
  RABBITMQ_DEFAULT_PASS: ZGVtbw==