apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-pod
  labels: 
    component: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: frontend-app
  template:
    metadata:
      labels:
        component: frontend-app
    spec:
      containers:
        - name: conv-app
          image: antonlarichev/short-app
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: first-service
spec:
  type: NodePort
  selector: 
    component: frontend-app
  ports:
  - port: 3000
    targetPort: 80
    nodePort: 31111
